AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation Execution Role for aws-cfn-infra-prod-deploy-pipeline

Resources:

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: cloudformation-execution-policy
          PolicyDocument:
            Version: "2012-10-17"

            Statement:
              # VPC, Networking, Security Groups, EC2
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
              # RDS
              - Effect: Allow
                Action:
                  - rds:*
                Resource: "*"
              # Secrets Manager
              - Effect: Allow
                Action:
                  - secretsmanager:*
                Resource: "*"
              # IAM Resources created by CloudFormation
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:TagRole
                Resource: "*"
              # CloudFormation
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
              # S3 
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource: "*"

Outputs:

  CloudFormationExecutionRoleArn:
    Description: CloudFormation Execution Role ARN
    Value: !GetAtt CloudFormationExecutionRole.Arn